from enum import StrEnum


class SourceSystem(StrEnum):
    LEGACY_DCP = "LEGACY_DCP"
    PJE = "PJE"
    EPROC = "EPROC"
    UNKNOWN = "UNKNOWN"
    MIGRATING = "MIGRATING"
    FAKE = "FAKE"


class SessionState(StrEnum):
    VALID = "VALID"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    UNAVAILABLE = "UNAVAILABLE"


class MonitorStatus(StrEnum):
    PENDING_INITIAL_CHECK = "PENDING_INITIAL_CHECK"
    ACTIVE_HEALTHY = "ACTIVE_HEALTHY"
    RETRY_SCHEDULED = "RETRY_SCHEDULED"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    MANUAL_ACTION_OPEN = "MANUAL_ACTION_OPEN"
    SOURCE_DIVERGENCE = "SOURCE_DIVERGENCE"
    MIGRATION_DETECTED = "MIGRATION_DETECTED"
    STALE_ALERTING = "STALE_ALERTING"
    DISABLED = "DISABLED"


class ErrorCode(StrEnum):
    AUTH_REQUIRED = "AUTH_REQUIRED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    SOURCE_DIVERGENCE = "SOURCE_DIVERGENCE"
    MIGRATION_DETECTED = "MIGRATION_DETECTED"
    PARSE_ERROR = "PARSE_ERROR"
    INVALID_DOCUMENT = "INVALID_DOCUMENT"
    TIMEOUT = "TIMEOUT"
    RATE_LIMIT = "RATE_LIMIT"
    LEASE_EXPIRED = "LEASE_EXPIRED"
    WORKER_MISCONFIGURED = "WORKER_MISCONFIGURED"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
    PROCESS_DISABLED = "PROCESS_DISABLED"


class JobStatus(StrEnum):
    PENDING = "PENDING"
    LEASED = "LEASED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    PAUSED = "PAUSED"


class JobAttemptStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class Sensitivity(StrEnum):
    INTERNAL = "INTERNAL"
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"


class ActorType(StrEnum):
    SYSTEM = "SYSTEM"
    ADMIN = "ADMIN"
    OPERATOR = "OPERATOR"
    LAWYER = "LAWYER"
